### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Bully268** [mookfist/repo#27]
I get the following error when trying to install the mi-light addon.
This was in v16 of Kodi
02:35:59 T:18446744072334593288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named importlib
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.mookfist-milights/service.py", line 1, in <module>
                                                from light import Lights, LightFadeThread
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.mookfist-milights/light.py", line 1, in <module>
                                                import milight
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.python-milight/lib/milight/__init__.py", line 5, in <module>
                                                from importlib import import_module
                                            ImportError: No module named importlib
                                            -->End of Python script error report<--

**Comment by mookfist** [comment]
hmm. as far as I'm aware, Kodi ships with its own python interpreter. Maybe this is different on Android? I will have to investigate.

**Comment by janbroersm** [comment]
Anyone succes on android? Still get the error on installation.

**Comment by mookfist** [comment]
importlib is not in use anymore. The new 0.2.0 is completely different. I'll install it on my android phone and see what happens.

**Comment by mookfist** [comment]
bah I tried installing it on my LG G5 without any luck. Not sure why and not even clear how I can debug this.
