### ISSUE TITLE
Still having issues :(

### ISSUE THREAD

**Issue by exxeraga** [mookfist/repo#38]
Hi, 
After you released the latest beta my bridge is being detected on scan but thats about as far as i managed to make it work. Im still unable to control the lights... I found these in kodi.log:

22:39:27.360 T:3945788320   ERROR: [mookfist-milights::Controller] Bridge not configured properly
22:39:35.566 T:3509244832  NOTICE: [mookfist-milights] Script - ARGV: ['scan']
22:39:35.566 T:3509244832  NOTICE: [mookfist-milights] Script - Command: scan - Args: {}
22:39:54.077 T:3509244832  NOTICE: [mookfist-milights] Selected Bridge: 192.168.1.20:5987 - Version 2
22:40:07.455 T:3531240352  NOTICE: [mookfist-milights] Script - ARGV: ['color_rgb', 'groups=all', 'r=255', 'g=0', 'b=0']
22:40:07.455 T:3531240352  NOTICE: [mookfist-milights] Script - Command: color_rgb - Args: {'r': '255', 'b': '0', 'g': '0', 'groups': 'all'}
22:40:09.831 T:3531240352  NOTICE: [mookfist-milights] Script - ARGV: ['brightness', 'groups=all', 'brightness=50']
22:40:09.831 T:3531240352  NOTICE: [mookfist-milights] Script - Command: brightness - Args: {'groups': 'all', 'brightness': '50'}
22:40:23.242 T:3531240352  NOTICE: [mookfist-milights] Script - ARGV: []
22:40:23.245 T:3531240352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.mookfist-milights/cmd.py", line 273, in <module>
                                                main(sys.argv[1:])
                                              File "/storage/.kodi/addons/script.service.mookfist-milights/cmd.py", line 248, in main
                                                cmd = argv[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by mookfist** [comment]
I have been putting in some effort lately on v0.2.0 which shoudl fix this problem.
